name: VoidGenPlus
version: ${project.version}
main: org.rafalohaki.voidgenplus.VoidGenPlus
api-version: '1.21'
load: STARTUP
author: rafalohaki
folia-supported: true
description: Generates a void world with a single bedrock block at spawn.
